### ISSUE TITLE
No support for http proxies

### ISSUE THREAD

**Issue by alexharv074** [neillturner/omnibus-ansible#7]
Any advice on how to implement appreciated.

**Comment by neillturner** [comment]
Yes well all the features are not there. -) 
I would enhance the script to look for the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables. 

actually when i check the code i think this line in ansible_playbook.rb: 
#{sudo_env('sh')} /tmp/ansible_install.sh #{version}
should already set the HTTP_PROXY, HTTPS_PROXY and NO_PROXY  env variables before calling ansible_install.sh if kitchen.yml has http_proxy, https_proxy or no_proxy set.

**Comment by alexharv074** [comment]
To be honest I find that `$http_proxy` and `$https_proxy` are completely ignored at all stages by Test Kitchen.

What I've had to do is create a `.kitchen.local.yml` and put in there something like:

```yaml
---
driver:
  driver_config:
    http_proxy: http://192.168.2.215:3128
    https_proxy: http://192.168.2.215:3128

provisioner:
  http_proxy: http://192.168.2.215:3128
  https_proxy: http://192.168.2.215:3128
```
